target 'BitBar' do
  platform :osx, '10.10'
  use_frameworks!

  pod 'EmitterKit', git: 'https://github.com/aleclarson/emitter-kit.git'
  pod 'FootlessParser', git: 'https://github.com/oleander/FootlessParser.git', branch: 'swift3.0'
  pod 'SwiftyTimer'
  pod 'DateTools'
  pod 'Cent'
  pod 'AsyncSwift'
  pod 'Files'
  pod 'Hue'
  pod 'SwiftyJSON'
  pod 'SwiftyUserDefaults'
  pod 'Sparkle'

  target 'BitBarTests' do
    inherit! :search_paths
    pod 'Quick'
    pod 'Nimble'
    pod 'SwiftCheck', git: 'https://github.com/typelift/SwiftCheck.git'
  end
end
