target 'BitBar' do
  platform :osx, '10.10'
  use_frameworks!

  pod 'EmitterKit'
  pod 'SwiftyTimer'
  pod 'DateTools'
  pod "Cent"
  pod "AsyncSwift"
  pod "Hue"
  pod "SwiftyJSON"
  pod 'FootlessParser', git: 'https://github.com/oleander/FootlessParser.git', branch: "swift3.0"

  target 'BitBarTests' do
    inherit! :search_paths
    pod 'Quick'
    pod 'Nimble'
    pod 'SwiftCheck', git: "https://github.com/typelift/SwiftCheck.git"
  end
end
