codesign = "/usr/bin/codesign"
env_cert = "Resources/bitbar.p12.enc"
cert = "Resources/bitbar.cer"

default_platform :mac
clear_derived_data

desc "Build BitBar.app to the current directory"
lane :build do;
  clean_build_artifacts
  gym
end

desc "Lint swift files in project"
lane :lint do; swiftlint mode: :lint; end

desc "Fix lint lint errors in project"
lane :fix do; swiftlint mode: :autocorrect; end

desc "Runs test suit"
lane :test do; scan; end

desc "Build and zip application"
lane :package do
  build
  zip path: "BitBar.app", output_path: "BitBar.zip"
end

desc "Generates a new version tag in git and XCode"
lane :tag do
  ensure_git_branch branch: "master"
  ensure_git_status_clean
  increment_version_number
  version = get_version_number()
  increment_build_number build_number: version
  commit_version_bump message: "Bump version to #{version}", force: true
  add_git_tag tag: "v#{version}"
  push_to_git_remote remote: "origin", force: false, tags: true
end

desc "Task to setup the project"
lane :setup do
  bundle_install
  cocoapods repo_update: true
end

desc "Import keys used for signing"
lane :import_keys do
  unless is_ci?
    next unless prompt boolean: true, text: "Are you sure you want to alter you local keychain?"
  end

  Dir.chdir ".." do
    openssl "aes-256-cbc -K $encrypted_34de277e100a_key -iv $encrypted_34de277e100a_iv",
      "-in", env_cert, "-out bitbar.p12 -d"
    security "create-keychain -p travis travis.keychain"
    security "default-keychain -s travis.keychain"
    security "unlock-keychain -p travis travis.keychain"
    security "set-keychain-settings -t 3600 -u travis.keychain "
    security "import bitbar.p12 -A -P $CERTPWD -k travis.keychain -T", codesign
    # security "import", cert, "-A -k travis.keychain -T", codesign
    security "set-key-partition-list -S apple-tool:,apple: -s -k travis travis.keychain"
  end
end

desc "Create a signed .app bundle for Github Releases"
lane :deploy do
  import_keys
  package
end

def security(*args)
  sh "security " + args.join(" ")
end

def openssl(*args)
  sh "openssl " + args.join(" ")
end
